import { Fraunces } from "next/font/google";
import Footer from './Components/Footer.jsx';
import Navbar from './Components/Navbar.jsx';
import "./globals.css";

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-[family-name:var(--font-fraunces)]" cz-shortcut-listen="true">
        <Navbar />

        {children}
        
        <Footer/>
      </body>
    </html>
  );
}