import { Fraunces } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Footer from './Components/Footer.jsx';
import Navbar from './Components/Navbar.jsx';
import { ThemeProvider } from "./Components/ThemeProvider.jsx";
import "./globals.css";

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
});

export const metadata = {
  title: "StudyNook-App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
     lang="en" suppressHydrationWarning className={`${fraunces.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-[family-name:var(--font-fraunces)] bg-white dark:bg-gray-900 text-black dark:text-white" cz-shortcut-listen="true">

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
                
              <Navbar />
              <main>
                {children} 
                 

             

<Toaster
  position="top-center"
  gutter={12}
  toastOptions={{
    duration: 4000,
    
    className:
      "!bg-white dark:!bg-gray-900 !text-gray-900 dark:!text-gray-100 !shadow-[0_8px_30px_-6px_rgba(0,0,0,0.15)] dark:!shadow-black/30 !rounded-xl !px-4 !py-3 !text-sm !font-medium",
     
    style: {},
    success: {
      iconTheme: {
        primary: "#2563eb",
        secondary: "#ffffff",
      },
      className:
        "!border-l-4 !border-l-blue-600 dark:!border-l-blue-500 !border-y !border-r !border-y-gray-200 !border-r-gray-200 dark:!border-y-gray-800 dark:!border-r-gray-800",
    },
    error: {
      iconTheme: {
        primary: "#dc2626",
        secondary: "#ffffff",
      },
      className:
        "!border-l-4 !border-l-red-600 dark:!border-l-red-500 !border-y !border-r !border-y-gray-200 !border-r-gray-200 dark:!border-y-gray-800 dark:!border-r-gray-800",
    },
    loading: {
      iconTheme: {
        primary: "#6b7280",
        secondary: "#ffffff",
      },
      className:
        "!border-l-4 !border-l-gray-400 dark:!border-l-gray-600 !border-y !border-r !border-y-gray-200 !border-r-gray-200 dark:!border-y-gray-800 dark:!border-r-gray-800",
    },
  }}
/>



              </main>
              
              <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}